-- Create Tables for socialaccount (Generated from sqlmigrate)

BEGIN;

CREATE TABLE "socialaccount_socialapp" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "provider" varchar(30) NOT NULL, "name" varchar(40) NOT NULL, "client_id" varchar(191) NOT NULL, "secret" varchar(191) NOT NULL, "key" varchar(191) NOT NULL, "provider_id" varchar(200) NOT NULL, "settings" jsonb NULL);
CREATE TABLE "socialaccount_socialaccount" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "provider" varchar(30) NOT NULL, "uid" varchar(191) NOT NULL, "last_login" timestamp with time zone NOT NULL, "date_joined" timestamp with time zone NOT NULL, "extra_data" jsonb NOT NULL, "user_id" bigint NOT NULL, CONSTRAINT "socialaccount_socialaccount_user_id_fk_accounts_customuser_id" FOREIGN KEY ("user_id") REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialaccount_provider_uid_uniq" UNIQUE ("provider", "uid"));
CREATE TABLE "socialaccount_socialtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" text NOT NULL, "token_secret" text NOT NULL, "expires_at" timestamp with time zone NULL, "account_id" integer NOT NULL, "app_id" integer NULL, CONSTRAINT "socialaccount_socialtoken_account_id_fk_socialaccount_socialaccount_id" FOREIGN KEY ("account_id") REFERENCES "socialaccount_socialaccount" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialtoken_app_id_fk_socialaccount_socialapp_id" FOREIGN KEY ("app_id") REFERENCES "socialaccount_socialapp" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialtoken_app_id_account_id_uniq" UNIQUE ("app_id", "account_id"));
CREATE TABLE "socialaccount_socialapp_sites" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "socialapp_id" integer NOT NULL, "site_id" integer NOT NULL, CONSTRAINT "socialaccount_socialapp_sites_socialapp_id_fk_socialaccount_socialapp_id" FOREIGN KEY ("socialapp_id") REFERENCES "socialaccount_socialapp" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialapp_sites_site_id_fk_django_site_id" FOREIGN KEY ("site_id") REFERENCES "django_site" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialapp_sites_socialapp_id_site_id_uniq" UNIQUE ("socialapp_id", "site_id"));

-- Manually insert into django_migrations to mark as applied
INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0001_initial', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0002_token_max_lengths', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0003_extra_data_default_dict', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0004_app_provider_id_settings', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0005_socialtoken_nullable_app', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0006_alter_socialaccount_extra_data', NOW()) ON CONFLICT DO NOTHING;

COMMIT;
