# Generated by Django 4.2.26 on 2026-01-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_notify_marketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Authentification à deux facteurs activée'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='Secret TOTP pour 2FA', max_length=32, null=True),
        ),
    ]
