from django.core.management.base import BaseCommand
from django.db import connection

class Command(BaseCommand):
    help = 'Apply recovery SQL directly via cursor'

    def handle(self, *args, **options):
        stmts = [
            # socialaccount_socialapp
            '''CREATE TABLE IF NOT EXISTS "socialaccount_socialapp" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "provider" varchar(30) NOT NULL, "name" varchar(40) NOT NULL, "client_id" varchar(191) NOT NULL, "secret" varchar(191) NOT NULL, "key" varchar(191) NOT NULL, "provider_id" varchar(200) NOT NULL, "settings" jsonb NULL);''',
            
            # socialaccount_socialaccount
            '''CREATE TABLE IF NOT EXISTS "socialaccount_socialaccount" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "provider" varchar(30) NOT NULL, "uid" varchar(191) NOT NULL, "last_login" timestamp with time zone NOT NULL, "date_joined" timestamp with time zone NOT NULL, "extra_data" jsonb NOT NULL, "user_id" bigint NOT NULL, CONSTRAINT "socialaccount_socialaccount_user_id_fk_accounts_customuser_id" FOREIGN KEY ("user_id") REFERENCES "accounts_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialaccount_provider_uid_uniq" UNIQUE ("provider", "uid"));''',
            
            # socialaccount_socialtoken
            '''CREATE TABLE IF NOT EXISTS "socialaccount_socialtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" text NOT NULL, "token_secret" text NOT NULL, "expires_at" timestamp with time zone NULL, "account_id" integer NOT NULL, "app_id" integer NULL, CONSTRAINT "socialaccount_socialtoken_account_id_fk_socialaccount_socialaccount_id" FOREIGN KEY ("account_id") REFERENCES "socialaccount_socialaccount" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialtoken_app_id_fk_socialaccount_socialapp_id" FOREIGN KEY ("app_id") REFERENCES "socialaccount_socialapp" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialtoken_app_id_account_id_uniq" UNIQUE ("app_id", "account_id"));''',
            
            # socialaccount_socialapp_sites
            '''CREATE TABLE IF NOT EXISTS "socialaccount_socialapp_sites" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "socialapp_id" integer NOT NULL, "site_id" integer NOT NULL, CONSTRAINT "socialaccount_socialapp_sites_socialapp_id_fk_socialaccount_socialapp_id" FOREIGN KEY ("socialapp_id") REFERENCES "socialaccount_socialapp" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialapp_sites_site_id_fk_django_site_id" FOREIGN KEY ("site_id") REFERENCES "django_site" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "socialaccount_socialapp_sites_socialapp_id_site_id_uniq" UNIQUE ("socialapp_id", "site_id"));''',

            # Insert migrations
            "INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0001_initial', NOW()) ON CONFLICT DO NOTHING;",
            "INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0002_token_max_lengths', NOW()) ON CONFLICT DO NOTHING;",
            "INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0003_extra_data_default_dict', NOW()) ON CONFLICT DO NOTHING;",
            "INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0004_app_provider_id_settings', NOW()) ON CONFLICT DO NOTHING;",
            "INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0005_socialtoken_nullable_app', NOW()) ON CONFLICT DO NOTHING;",
            "INSERT INTO django_migrations (app, name, applied) VALUES ('socialaccount', '0006_alter_socialaccount_extra_data', NOW()) ON CONFLICT DO NOTHING;",
            
            "INSERT INTO django_migrations (app, name, applied) VALUES ('sites', '0001_initial', NOW()) ON CONFLICT DO NOTHING;",
            "INSERT INTO django_migrations (app, name, applied) VALUES ('sites', '0002_alter_domain_unique', NOW()) ON CONFLICT DO NOTHING;"
        ]

        with connection.cursor() as cursor:
            for sql in stmts:
                try:
                    self.stdout.write(f"Executing: {sql[:50]}...")
                    cursor.execute(sql)
                    self.stdout.write(self.style.SUCCESS("OK"))
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f"Error: {e}"))
