# Generated by Django 6.0.1 on 2026-01-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='trigger_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
