# Generated by Django 4.2.26 on 2025-12-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='config_action',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='area',
            name='config_reaction',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
