# Generated by Django 5.2.5 on 2025-12-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_area_config_action_area_config_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="name",
            field=models.CharField(default="Untitled Area", max_length=255),
        ),
    ]
