# Generated by Django 5.2.5 on 2026-01-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_area_trigger_state"),
        ("automation", "0003_area_name"),
    ]

    operations = []
