# Generated by Django 4.2.26 on 2026-01-18 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_merge_0002_area_trigger_state_0003_area_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='config_schema',
        ),
        migrations.RemoveField(
            model_name='action',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='area',
            name='action_parameters',
        ),
        migrations.RemoveField(
            model_name='area',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='area',
            name='reaction_parameters',
        ),
        migrations.RemoveField(
            model_name='area',
            name='trigger_state',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.AddField(
            model_name='action',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='area',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='area',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reaction',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='service',
            name='display_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='area',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='automation.action'),
        ),
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='automation.reaction'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='automation__name_25085a_idx'),
        ),
    ]
